name: customerpipeline
version: 1.0
config-version: 2

profile: customerpipeline

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  customerpipeline:
    +materialized: view
