version: 2

models:
  - name: dim_customer
    description: Customer dimension table containing unique customer records.
    columns:
      - name: customer_id
        description: Unique ID for each customer
        tests:
          - not_null
          - unique
      - name: customer_email
        description: Email address of the customer
        tests:
          - not_null

  - name: dim_product
    description: Product dimension table with product details.
    columns:
      - name: product_id
        description: Unique ID for each product
        tests:
          - not_null
          - unique
      - name: unit_price
        description: Unit price of the product
        tests:
          - not_null

  - name: dim_date
    description: Date dimension with calendar attributes.
    columns:
      - name: date_id
        description: Unique date key (primary key)
        tests:
          - not_null
          - unique

  - name: fact_orders
    description: Fact table containing customer orders with foreign keys to dimensions.
    columns:
      - name: order_id
        description: Unique order ID
        tests:
          - not_null
          - unique
      - name: customer_id
        description: Foreign key to customer
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: product_id
        description: Foreign key to product
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_id
      - name: date_id
        description: Foreign key to date
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_id
