version: 2

sources:
  - name: raw
    database: CUSTOMER_DB
    schema: PUBLIC
    tables:
      - name: dim_customer
      - name: dim_product
      - name: dim_date
      - name: fact_order